### ISSUE TITLE
Summernote-rails not working

### ISSUE THREAD

**Issue by rasool-sb** [summernote/summernote-rails#11]
Hi, am new to rails, am using summernote for my app, I have followed the whole document and did as per the documentation. but, the editor is not dispalying in my text_area.  means it just shows a blank text area box with out any buttons, the details are below.

In my gem file:

      gem 'simple_form', '2.1.1'
      gem 'summernote-rails', '0.4.0'
      gem 'bootstrap-sass', '3.1.1.1'
      gem 'bootstrap-will_paginate', '0.0.10'
      gem 'font-awesome-sass-rails', '3.0.2.2'

In app/assets/javascripts/application.js

      //= require jquery
      //= require jquery_ujs
      //= require bootstrap
      //= require summernote.min
      //= require_tree .

in app/assets/stylesheets/application.css,
      *= require_self
      *= require_bootstrap
      *= require_font-awesome
      *= require_summernote
      *= require_tree .
In my events/_form.html.erb
      <%= f.input :error_detail, label:'Summary', class:'summernote', input_html:{class:'form-control'} %>
in my app/assets/javascripts/events.js.coffee
      $ ->

      # to set summernote object
      # You should change '#event_error_detail' to your textarea input id
      summer_note = $('#event_error_detail')
      # to call summernote editor
      summer_note.summernote
      # to set options
      height:300
      lang: 'en'
      # toolbar: [
                # ['insert', ['picture', 'link']], // no insert buttons
                # ["table", ["table"]],
                # ["style", ["style"]],
                # ["fontsize", ["fontsize"]],
                # ["color", ["color"]],
                # ["style", ["bold", "italic", "underline", "clear"]],
                # ["para", ["ul", "ol", "paragraph"]],
                # ["height", ["height"]],
                # ["help", ["help"]]
             #]
      # to set code for summernote
      summer_note.code summer_note.val()
      # to get code for summernote
      summer_note.closest('form').submit ->
      # alert $('#event_error_detail').code()
      summer_note.val summer_note.code()
      true

The error am getting in my firefox browser's error console:

      TypeError: summer_note.summernote is not a function

MY ENVIRONMENT DETAILS: Ruby 1.9.3 and Rails 3.2.8 Ubuntu 12.4

Please help me where am i doing wrong.., Please I need help.

**Comment by blairanderson** [comment]
@rasool-sb try this in your gemfile:

```ruby
gem 'summernote-rails', require: 'summernote/rails'
```

**Comment by chrise86** [comment]
I'm also having issues when trying to use `@import "summernote";`:

    Sass::SyntaxError - File to import not found or unreadable: summernote.

**Comment by chrise86** [comment]
Same for Javascript too, even with that require line, both sourced from Github master and rubygems.

**Comment by seapy** [comment]
In scss use like this `@import "summernote/summernote";` 

javascript not works? can you check `summernote-rails-test` sample app it works.

**Comment by chrise86** [comment]
I tried that, and `summernote/index` - neither worked.

**Comment by seapy** [comment]
what's your gem version? 

```
$ bundle exec gem list summernote-rails

*** LOCAL GEMS ***

summernote-rails (0.6.1)
```

**Comment by xn** [comment]
I had this issue and got: `@import "summernote/summernote";` to make it work.

**Comment by adrazek** [comment]
I have the same issue, I tried all the answers and neither works ...

**Comment by adrazek** [comment]
Ok, I realize that it works if I import your lib in my rails app, not if I import your lib in an engine who is imported in my rail app. Something to do to got it working ?

**Comment by dannolan** [comment]
I'm also having the same problem using Summernote in an engine in an app. I'll look through the source and see what I can do

**Comment by luciuschoi** [comment]
This gem was bumped up to 0.6.7.0 version before 7 days.
And so you should confirm the directive of `@import 'summernote';` in application.scss.
(You need to read the updated README.md.)
