### ISSUE TITLE
html_safe and escaping javascript

### ISSUE THREAD

**Issue by karlingen** [summernote/summernote-rails#15]
Obviously using .html_safe or raw() on the content is not a good idea if the saved data is not escaped from javascript. Inserting <script>alert('hacked');</script> when in html-mode will pop open an alert box when the user views the post. 

Any ideas on how to properly escape javascript from the content that is being saved? 
Using this gem is probably an option: https://github.com/rgrove/sanitize
But I wanted to make sure that I am not doing this the wrong way - adding an additional gem just to sanitize malicious input.

**Comment by seapy** [comment]
i think whitelist-based escape is best.(https://github.com/rgrove/sanitize is whitelist-based)

Choose whitelist is depends on application, some application not allow script but another application allow.
