### ISSUE TITLE
Global override of .hidden-xs in bs3.css seems problematic

### ISSUE THREAD

**Issue by vincentzhezhang** [summernote/summernote-rails#19]
`/* line 5866, /Users/vincent/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/summernote-rails-0.6.1/vendor/assets/stylesheets/summernote/bs3.css */`

```
.hidden-xs {
  display: block !important;
}
```

This global override of bootstrap class break any element that using `.hidden-xs` class if it's css attribute `display` is not `block`

**Comment by seapy** [comment]
thanks :) fixed and release
