### ISSUE TITLE
unable to load summernote editor

### ISSUE THREAD

**Issue by rasool-sb** [summernote/summernote-rails#21]
Hellow.,

I am unable to load summernote editor...please correct and please guide me where am doing wrong., please see the details below

My environment details:-
    1) OS : Ubuntu 14.04
    2) Ruby 1.9.3
    3) Rails 3.2.21
    4) Browser : firefox 37

In my Gemfile:

    gem 'summernote-rails', '~> 0.6.5.0'
    gem 'font-awesome', '~> 4.2.0.0'
    gem 'bootstrap-sass', '3.1.1.1' 

In my application.js file

    //= require jquery
    //= require jquery_ujs
    //= require bootstrap
    //= require summernote
    //= require_tree .

In my application.css.scss

    *= require_self
    *= require_bootstrap
    *= require font-awesome
    *= require summernote
    *= require_tree .

In my simple_form_for form

    <%= f.input :error_detail, label: " Please explain with full details", class: :summernote %>

after all doing this, it displays plain text box am attaching screen shot for verification please find the attachment
![summernote](https://cloud.githubusercontent.com/assets/1423463/7400085/f2bb949c-eed7-11e4-809b-b7ee3c826110.png)

In my firefox browser getting error like

    <textarea class="text required form-control" cols="40" id="event_error_detail" multipart="true" name="event[error_detail]" rows="20"></textarea>

Please let me know if any information needed from me.. Thanks.

**Comment by seapy** [comment]
Are you insert javascript code?
this code enable summernote.

```html
<div id="summernote">Hello Summernote</div>

<script type="text/javascript">
  $(document).ready(function() {
    $('#summernote').summernote();
  });
</script>
```

**Comment by rasool-sb** [comment]
Thanks for reply, Yes, I have enable the javascript in my app/assets/javascripts/application.js, AND posts.js same as you mentioned above, I get the same plain text area, please help me... thank you.

**Comment by rasool-sb** [comment]
Any how using this coffee script got solved my issue, am really so so happy to use this auspicious gem, am great fan of this haha., Thank you so much for kind support.
