### ISSUE TITLE
Image size restriction

### ISSUE THREAD

**Issue by rasool-sb** [summernote/summernote-rails#22]
Hi,

Is there any way to restrict the size of the image, so the people can't allow themselves to upload the image more than 1 mb in size, something like this.. AND

Is there any way to upload the images in to Amazon S3..??? please help me... 

Thanking you,
SBR

**Comment by seapy** [comment]
You can restrict image size, if you upload image using `base64 encoded data image`(default).
option is `maximumImageFileSize`(bytes, 1048576 bytes = 1mb)

```javascript
$('.summernote').summernote({
  maximumImageFileSize: 1048576
});
```

upload image to Amazon S3 is available, but you implement that feature.
using `onImageUpload` callback. 

summernote/summernote#72 will help you.

**Comment by rasool-sb** [comment]
WooOOooW... huge thanks to you and to this awesome gem... \m/

**Comment by thebizkit** [comment]
> You can restrict image size, if you upload image using `base64 encoded data image`(default). option is `maximumImageFileSize`(bytes, 1048576 bytes = 1mb)
> 
> ```js
> $('.summernote').summernote({
>   maximumImageFileSize: 1048576
> });
> ```
> 
> upload image to Amazon S3 is available, but you implement that feature. but that case `maximumImageFileSize` is not working. implement your self too. using `onImageUpload` callback.
> 
> [summernote/summernote#72](https://github.com/summernote/summernote/issues/72) will help you.

Is it also possible to check the total size of all images being inserted into a single editor when they hit the Save button?
