### ISSUE TITLE
"summernote is not a function" TypeError

### ISSUE THREAD

**Issue by ErinJoan** [summernote/summernote-rails#23]
Hello,

I'm trying to use this gem, and I believe I followed the instructions correctly, but it seems like the summernote.js file is not being loaded? I keep getting the "summernote is not a function" TypeError.

I downloaded the files and put them in my app/assets/javascripts folder.

My application.js file looks like this:
//= require jquery
//= require jquery_ujs
//= require turbolinks
//= require bootstrap
//= require summernote
//= require_tree .

And I copied and pasted the script into my view:

  <div id="summernote">Hello Summernote</div>

    <script type="text/javascript">
      $(document).ready(function() {
        $('#summernote').summernote();
      });
    </script>

But I keep getting an error. Can you help me?

![screen shot 2015-05-28 at 3 02 46 pm](https://cloud.githubusercontent.com/assets/4401585/7872189/07475a16-054b-11e5-848d-b1b2a896f73a.png)

**Comment by rasool-sb** [comment]
I think.. the java script code should be in app/assets/javascripts/application.js, please paste the code in application.js file, and please check.

  <script type="text/javascript">
      $(document).ready(function() {
          $('#summernote').summernote();
      });
  </script>

have you set the summernote assets in app/assets/stylesheets/application.css.scss..?? if not.. please assign it as:

*= require font-awesome
*= require summernote

**Comment by ErinJoan** [comment]
I fixed it. Turns out I needed to turn off turbolinks and move my jquery call in the HTML head above the javascript call. 

  <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application', media: 'all' %>
