### ISSUE TITLE
can we set the line height to 1.0

### ISSUE THREAD

**Issue by rasool-sb** [summernote/summernote-rails#24]
Hi,
    By default the line height is set to 1.4, can we change that to 1.0..?? is there a way..??

Thanks and Best Regards,

**Comment by seapy** [comment]
hi, this is summernote issue not summernote-rails.
https://github.com/summernote/summernote/issues/1087 is similar your question

**Comment by rasool-sb** [comment]
You are the one fella who continually supports to the people for free, Hats off to you,.. :) +1:

**Comment by rasool-sb** [comment]
You are the one guy who continually supports to the people for free, Hats off to you,.. :) :+1:
