### ISSUE TITLE
Update to v0.6.9 of summernote?

### ISSUE THREAD

**Issue by san** [summernote/summernote-rails#29]
Would it be possible to update to the latest version (v0.6.9) of summernote any time soon?

Thanks.

**Comment by hackerwins** [comment]
@san v0.6.9.0 is released now. This is first time by myself on this repository. If there is problem, Let me know. Thanks.

**Comment by rasool-sb** [comment]
Hi, I am unable to find the version 0.6.9 in rubygems.org, please help!

**Comment by san** [comment]
@hackerwins It does look like released, but as previous commenter said, when I update from github, I still the previous release. I am not sure how to do it, but may be one step is missing that registers the release with rubygems.org.

**Comment by san** [comment]
@hackerwins You may need to do something like this? http://guides.rubygems.org/publishing/#publishing-to-rubygemsorg

Not sure though.

**Comment by san** [comment]
@hackerwins You may need to do this? http://guides.rubygems.org/publishing/#publishing-to-rubygemsorg

Not sure though.

**Comment by san** [comment]
@rasool-sb Feel free to use my branch until this is resolved:

`gem 'summernote-rails', github: 'san/summernote-rails'`

**Comment by rasool-sb** [comment]
Hi @san Thank you so much, :)

**Comment by hackerwins** [comment]
@san thanks I'll try

**Comment by seapy** [comment]
@rasool-sb @san sorry for lazy update
updated rubygems :)

**Comment by rasool-sb** [comment]
Hurray... Thank you so much @seapy @san Love you and Love this Awesome Gem.. :)
