### ISSUE TITLE
content of the summernote is not posted to the controller

### ISSUE THREAD

**Issue by Jusliang** [summernote/summernote-rails#31]
Did you test if the controller can get the user input of the summernote? 

On my end, my application controller cannot get the value of the summernote. 
## Here is my view.html.erb

```
                <%= simple_form_for :question, url: { action: 'submit' } do |f| %>
                    <%= f.hidden_field :course_id, value: @current_course %>
                    <div class="form-group">
                      <%= f.label :question_title, "Question Title" %>
                      <%= f.text_field :question_title, autofocus: true, class: "form-control placeholder-no-fix", placeholder: "What's you questions? Be specific" %>
                    </div>
                    <div class="form-group">
                      <label for="description">Description</label>
                      <%= f.input :question_content, input_html: { class: 'summernote' } %>
                    </div>
                    <div class="text-right">
                      <%= f.submit "Save", class: "btn btn-primary" %>
                    </div>
                <% end %>
```

---

but the value of :question_content is not be post back.

ActionController::Parameters (3 elements)
'course_id' = "12"
'question_title' = "sdfsdfs"
## 'question_content' = ""

The version of summernote i am using is v0.6.10.0.

**Comment by unsouled** [comment]
@Jusliang 

did you try this?
```ruby
<%= f.input :question_content, as: 'summernote'  %>
```

**Comment by hackerwins** [comment]
@unsouled :+1:

**Comment by Jusliang** [comment]
@unsouled  yes, I tried, same issue

**Comment by seapy** [comment]
@Jusliang show your html source, not simple form source

**Comment by unsouled** [comment]
@Jusliang
If you use rails4 ( or strong_parameter gem ), check that 'question_content' parameter was permitted by your controller.

**Comment by riseshia** [comment]
is there any progress? I will close this if not.
