### ISSUE TITLE
Summernote duplicating fields on edit form

### ISSUE THREAD

**Issue by jtansley** [summernote/summernote-rails#34]
Hello,

The summernote fields on my edit form aren't loading right. When I load the edit form (editing an existing object in the database), it populates all of the fields on the page with the actual database value from the first field. In my app, I have various fields...the first one is called description. The summernote fields are all populated with the value of the description field. 

I verified that the database still holds the correct values of the fields. In fact, when I view the page source of the loaded edit form, the html shows that the values are all being properly loaded. The javascript seems to be overwriting them. It must be an issue with my meds.coffee script. Can you please help me fix this issue? How do I properly load multiple fields in the coffee script file?

My repo is here:
https://github.com/jtansley/explainmymedicine/

Thanks!

EDIT: 

To clarify, I'm experiencing the issue on this edit form:
https://github.com/jtansley/explainmymedicine/blob/master/app/views/meds/edit.html.erb/

**Comment by luciuschoi** [comment]
I have just cloned your repo and replaced the whole meds.coffee file as follows:

```coffee
$ ->
  $('[data-provider="summernote"]').each ->
    $(this).summernote()
```

It also worked properly on editing an presisted record and so I could see the multiple text fields held each corresponding attribute value correctly.

Good luck!

**Comment by luciuschoi** [comment]
In meds.coffee file of your repo, you called summernote editor twice for individual fields.

First call is as follows:

```coffee
$ ->
  $('[data-provider="summernote"]').each ->
    $(this).summernote()
```

Second calls are:

```coffee
$ ->
  # to call summernote editor
  summer_note.summernote
  summer_note2.summernote
  summer_note3.summernote
  summer_note4.summernote
  summer_note5.summernote
  summer_note6.summernote
  summer_note7.summernote
    # to set options
    height:300
    codemirror:
      lineNumbers: true
      tabSize: 2
      theme: "solarized light"
```

Therefore, you must remove code lines for second calls.

If you want to add some options to a certain summernote editor, you must not add `as: :summernote` option for corresponding field input in form view file and call summernote editor for it additionally in meds.coffee.

So, you may modify the form view file(edit.html.erb) as follows:

```erb 
<div class = "container">
<fieldset>
  </p><h2>Edit Medicine</h2></p>
  <%# if user_signed_in? && current_user.is_admin == true %>
  <%= simple_form_for @med, class: "form-horizontal" do |f| %>
    <div class="form-group">
    <%= f.input :brand_name, required: true %>
    </div>

    <div class="form-group">
    <%= f.input :generic_name, required: true %>
    </div>

    <div class="form-group">
    <%= f.input :description, as: :summernote, :id => 'description' %>
    </div>

    <div class="form-group">
    <%= f.input :reactions, as: :summernote, :id => 'reactions' %>
    </div>

    <div class="form-group">
    <%= f.input :interactions, as: :summernote, :id => 'interactions' %>
    </div>

    <div class="form-group">
    <%= f.input :implementation, as: :summernote, :id => 'implementation' %>
    </div>

    <div class="form-group">
    <%= f.input :availability, as: :summernote, :id => 'availability' %>
    </div>

    <div class="form-group">
    <%= f.input :caution, as: :summernote, :id => 'caution' %>
    </div>

    <div class="form-group">
    <%= f.input :warnings, :id => 'warnings' %>
    </div>

    <%= f.button :submit, class: "btn btn-primary" %> </div>
  <% end %>
  <%# end %>
</fieldset>
</div>
```

(In the above, you could find the absence of `as: :summernote` option for `f.input :warnings, :id => 'warnings'`)

and also meds.coffee file as follows:

```coffee
$ ->
  $('[data-provider="summernote"]').each ->
    $(this).summernote
      height:50

  summer_note7 = $('#med_warnings')
  summer_note7.summernote
    # to set options
    height:300
    codemirror:
      lineNumbers: true
      tabSize: 2
      theme: "solarized light"
```

(In the above, you could find the additional code line `height:50`.)

I wish it helps you. Good luck~

**Comment by rasool-sb** [comment]
@luciuschoi +1:

**Comment by rasool-sb** [comment]
@luciuschoi +1

**Comment by rasool-sb** [comment]
@luciuschoi :+1:

**Comment by jtansley** [comment]
Thank you so much for the thorough explanation! This worked perfectly!! I learned a great deal here.
