### ISSUE TITLE
standalone version (without bootstrap)

### ISSUE THREAD

**Issue by stereodenis** [summernote/summernote-rails#35]
here sad
https://github.com/summernote/summernote/issues/1324#issuecomment-145011223
that summernote has lite version
https://github.com/summernote/summernote/blob/develop/lite.html
Is it possible to implement it in summernote-rails?

**Comment by seapy** [comment]
summernote-lite is not yet released
but have a plan to support summernote-lite

**Comment by JimCook57** [comment]
Is there a target date for summernote-lite to be released?  Looking forward to it.

**Comment by seapy** [comment]
@JimCook57 Not decided yet 'summernote-lite' release date
