### ISSUE TITLE
Precompilation error

### ISSUE THREAD

**Issue by guyaloni** [summernote/summernote-rails#37]
I have a LESS-based rails application.
Trying to add summernote I added these lines:

**Gemfile:**

```
gem 'font-awesome-rails'
gem 'summernote-rails'
gem 'bootstrap-sass'
```

**application.css:**

```
*= require font-awesome
*= require summernote
```

In local everything works fine.
When I commit the application to heroku I get the following error:

```
Sass::SyntaxError: Undefined variable: "$alert-padding".
   (in /tmp/build_xxx/vendor/bundle/ruby/2.1.0/gems/bootstrap-sass-3.3.1.0/assets/stylesheets/bootstrap/_alerts.scss:10)
```

I guess I miss the SASS variables, but have no idea how to add them without create any conflict with the LESS code.

**Comment by seapy** [comment]
@guyaloni i think it's a bootstrap-sass issue or need `sass-rails` gem. 
if you don't want `sass-rails` gem, find another bootstrap gem like `https://github.com/metaskills/less-rails-bootstrap`

**Comment by guyaloni** [comment]
I have both `sass-rails` and `less-rails-bootstrap` gems in my Gemfile.
I have sass files included, I checked and `_variables.scss` is included by `application.scss` first.
Still, I get this error.

**Comment by seapy** [comment]
How about `rake asset:precompile` in local? still error?
and if you delete `bootstrap-sass` from Gemfile, error message is not same.

**Comment by guyaloni** [comment]
I wonder whether it is possible to use `summernote-rails` without sass.
I had a problem that the modal (image, link, etc..) is stayed behind, and I solved it adding `z-index` to it. As far as I remember without sass it didn't help..

**Comment by seapy** [comment]
`summernote-rails` is not dependent sass. it's just css(https://github.com/summernote/summernote-rails/blob/master/vendor/assets/stylesheets/summernote.css)
but `summernote-rails` need bootstrap.

**Comment by guyaloni** [comment]
As I mentioned, I use in my project `less-rails-bootstrap` gem. 
When I include `bootstrap-sass` as indicated in this gem instructions, I get the precompilation error.
When i remove it, the url/image modal dialog box appears behind the gray layer and not accesible (I have to refresh). 
Any idea?

**Comment by seapy** [comment]
hum.. how about change application.css require order like this.

1. bootstrap
2. font-awesome
3. summernote

**Comment by guyaloni** [comment]
This is my `application.scss` looks like at the moment:

    @import "bootstrap-sprockets";
    @import "bootstrap/variables";
    @import "bootstrap/mixins";
    @import "bootstrap";
    /*
     * This is a manifest file that'll be compiled into application.css, which will include all the files
     * listed below.
     *
     * Any CSS and SCSS file within this directory, lib/assets/stylesheets, vendor/assets/stylesheets,
     * or vendor/assets/stylesheets of plugins, if any, can be referenced here using a relative path.
     *
     * You're free to add application-wide styles to this file and they'll appear at the top of the
     * compiled file, but it's generally better to create a new file per style scope.
     *
     *= require_self
     *= require custom_bootstrap/custom_bootstrap
     *= require custom
     *= require social-share-button
    
     *= require bootstrap-datetimepicker
    
     *= require dataTables/jquery.dataTables
     *= require dataTables/src/demo_table_jui
     *= require pricing
     
     *= require jquery.fileupload-ui
    
     *= require font-awesome
     *= require social-buttons-3.css
    
     *= require summernote
     */

At the end of `application.js` I have these lines:

        :
        :
    //= require bootstrap
    //= require summernote
    //= require summernote/locales

**Comment by seapy** [comment]
how about don't mix import and require in 'application.scss' or require_self is under the `require summernote`

**Comment by guyaloni** [comment]
Again, the problem is that I have `less` files in my project, and as far as I know `less` and `sass` are not compatible with each other.

**Comment by factorjx** [comment]
on version 0.8.1.1 while use RAILS_ENV=production rake assets:precompile get ArgumentError: invalid byte sequence in utf-8
on version 0.7.1.0 it's all good

**Comment by riseshia** [comment]
if you have same issue until now, please reopen again.
