### ISSUE TITLE
After save wysiwyg showing html markup

### ISSUE THREAD

**Issue by Grubah** [summernote/summernote-rails#39]
Hi!
This is bothering me for a few hours now... Every thing worked fine before, and I haven't worked on anything that is related to summernote. But when i tried editing the content today, I got this problem.

When I am creating new content, summer note works as expected, but when I try to edit the saved content i get HTML markup in WYSIWYG mode in summer note. 

Any one has any idea? Thanks for help.

Similar problem is described here: https://stackoverflow.com/questions/34486460/summernote-showing-html-markup

**Comment by seapy** [comment]
sorry it's summernote 0.7.0 bug. before releases 0.7.1 use summernote-rails version 0.6.16.0
see this issue https://github.com/summernote/summernote/issues/1468

**Comment by brianlittmann** [comment]
If you want to patch the `summernote` source before 0.7.1 is released (expected Dec. 31), reference:
https://github.com/summernote/summernote/issues/1468#issuecomment-162330296

Or if you want to write some extra JavaScript as a workaround, reference:
https://github.com/summernote/summernote-rails/issues/38#issuecomment-167679385

**Comment by seapy** [comment]
Thanks, 
but summernote-rails gem don't fix summernote core(.js, .css)
waiting released 0.7.1

just a minute ago removed summernote-rails gem version 0.7.0.0 from rubygems

**Comment by seapy** [comment]
summernote 0.7.1 will be released tomorrow

**Comment by Grubah** [comment]
Thanks everybody for help! I just reverted to version 0.6.16.0.

**Comment by seapy** [comment]
v0.7.1.0 released checkout please

**Comment by stereodenis** [comment]
@seapy reproduce this issue with 0.7.1.0

**Comment by sureseam** [comment]
Also seemed to have hit this; however the SummerNote stuff comes back to life if I hit refresh.  This suggests a turbolink dimension to the problem; where most of the page isn't being reloaded and therefore some JS handlers do not get run when we need them to.  This appears to be the case with version '0.6.16.0' and '0.7.1.0'.  Not sure what the canonical solution should be - I put some JS script into the end of the form and hey presto.

**Comment by mbsankar84** [comment]
why some of the old .doc bullets are not properly rendering / not rendering. is ther any issue and how we need a page breaks, header ,footer (like as ms word.doc ) for summer note ??
