### ISSUE TITLE
insert video get error

### ISSUE THREAD

**Issue by xguox** [summernote/summernote-rails#4]
I am trying to use summernote in my project, but I got a strange error. 
this error happened both with and without using summernote-rails gem in  rails 4. And only  with  **chrome and safari** (webkit?).  **Everything  under IE and firefox is ok!**

I also tried the [summernote-test](http://github.com/rorlab/summernote-test) 
All situation are the same.

When I create or update a post with video, they come successfully  except the wrong redirect_to.

the url become `data:,` , the page become blank.  the log did not display any bug code.  
this  made me so feel strange.

So , did u try to insert  video,  and  is everything is ok? 
![image](https://f.cloud.github.com/assets/1177920/1885697/3c118ab2-79d5-11e3-95c8-9e70a330b80d.png)

**Comment by seapy** [comment]
this issue not fixed? 
@rorlab say this is delayed reason release rubygems. 
but currently summbernote-rails is released rubygems, so i close this issue.

if you get same error, please reopen
