### ISSUE TITLE
0.7.0 yanked from rubygems

### ISSUE THREAD

**Issue by thekendalmiller** [summernote/summernote-rails#40]
https://rubygems.org/gems/summernote-rails/versions/0.7.0.0

We were just setting up a new environment, and bundle install failed. 0.7.0 has been removed from rubygems.org. It was there yesterday.

Will there be a new release?
What was the reason that it was yanked? I browsed issues here and on summernote but didn't see any related to security vulnerabilities.

Thanks

**Comment by seapy** [comment]
@thekendalmiller it's related https://github.com/summernote/summernote-rails/issues/39 

summernote 0.7.0 has big issue. so i yank 0.7.0.0 version.
summernote 0.7.1 will be released in this year

**Comment by thekendalmiller** [comment]
Than yous for the information @seapy

**Comment by seapy** [comment]
v0.7.1.0 released checkout please
