### ISSUE TITLE
Without Bootstrap?

### ISSUE THREAD

**Issue by bl4ckdu5t** [summernote/summernote-rails#42]
I'm not using bootstrap and I don't use it on a lot of projects. Does the editor break without it? Because I wouldn't want to load an entire framework I don't need just for a component

**Comment by riseshia** [comment]
Now, Summernote works on  Bootstrap and jQuery, Font-Awesome. Hence, you should use that if you want to use summernote. you still expect to use although this reason, I recommend you to suggest this idea to [summornote issue](https://github.com/summernote/summernote/issues).

**Comment by bl4ckdu5t** [comment]
Thanks I'll do that
