### ISSUE TITLE
Upgrade to v0.8.0

### ISSUE THREAD

**Issue by teohm** [summernote/summernote-rails#45]
@seapy Any plan to release a new version with summernote v0.8.0? This new version contains some bug fixes that I need. 

I'm happy to submit PR but need some guides on how to add fonts properly into the gem, as v0.8.0 has replaced font-awesome with own font.

**Comment by seapy** [comment]
Hi, i will update today

**Comment by teohm** [comment]
Sweet! @seapy let me know if you need someone to test it

**Comment by seapy** [comment]
@teohm Hi, updated to summernote 0.8.1,
Use summernote-rails 0.8.1.1 and check please production environment
