### ISSUE TITLE
Adding html tag <br> more than once

### ISSUE THREAD

**Issue by rasool-sb** [summernote/summernote-rails#47]
Hi, 
    While copy paste the text continually 10 times, the html tag `<br>` adding to itself 10 times at the end of the paragraph, I have also tested with your sample app "example", here is the sample what I got in my app,

`<p>testing comment text editing tool box testing comment text editing tool box testing comment text editing tool box testing comment text editing tool box testing comment text editing tool box testing comment text editing tool box testing comment text editing tool box testing comment text editing tool box testing comment text editing tool box testing comment text editing tool box <br><br><br><br><br><br><br><br><br><br><br></p>`

**Comment by riseshia** [comment]
Because of characteristic of this problem, this problem may be handled on summernote.
It could be occurred not only this gem, but also another backend unless handle useless tag.
according to the policy of this gem, we don't have plan to handle these problem now.
Thanks your report! :)
