### ISSUE TITLE
Can't set content of summernote textarea with capybara

### ISSUE THREAD

**Issue by danielfriis** [summernote/summernote-rails#48]
I just updated from `0.6.16.0` to `0.8.1.0` and now I can't figure out how to set content of a summernote textarea in order to test its integration with my rails app.

With `0.6.16.0`, this worked:

```
it "allows admins to add text blocks to events", js: true, focus: true do
    click_on "Add text block"
    expect(page).to have_content "Text block content"
    all("div[contenteditable]").last.set("Dummy text")
    click_on "Publish now"
    expect(page).to have_content "Event created successfully"
    expect(Event.last.text_blocks.last.text_attachment.content).to eq "Dummy text"
end
```

Now, it doesn't get set:

```
  1) events feature event creation adding content blocks allows admins to add text blocks to events
     Failure/Error: expect(Event.last.text_blocks.last.text_attachment.content).to eq "Dummy text"

       expected: "Dummy text"
            got: ""

       (compared using ==)
```

And unfortunately I need the `0.8.1.0` version for it's callbacks features.

**Comment by AndreiMotinga** [comment]
anything new here?

**Comment by riseshia** [comment]
not yet... anyone could make a example to reproduce this bug?

**Comment by JunichiIto** [comment]
@danielfriis I decided to call Summernote API via `execute_scrupt` like:

```ruby
script = <<-JS
$('.some-field').summernote('editor.insertText', 'This is awesome blog.');
JS
execute_script(script)
```

See also:

- http://stackoverflow.com/questions/30836587/how-to-set-text-into-summernote-textarea-with-capybara-poltergeist
- http://stackoverflow.com/questions/37835192/capybara-set-value-of-summernote-textarea

**Comment by riseshia** [comment]
I think that's enough. close it
