### ISSUE TITLE
try to save but did'nt saved 

### ISSUE THREAD

**Issue by wicky-info** [summernote/summernote-rails#51]
## can someone help me, I try to save text but did'nt save, this is my form.

`<form class="ui form">
<%= simple_form_for @forum do |f| %>
<%= f.input_field :title %>
<%= f.input_field :description %>
<%= f.input_field :content, as: :summernote %>
<%= f.submit "Buat artikel", class: "mini ui button olive" %>
<%= link_to "Cancel", :back, class: "mini ui button orange" %>
<% end %>
</form>

> `

**Comment by sureseam** [comment]
You should be using 'input' rather than 'input_field' on the summernote field.

The purpose of input_field is to leave out a lot of the sophistication of the input mechanism.

Happy hunting

**Comment by wicky-info** [comment]
oh, thanks @sureseam , I will try that.. cheers!!

**Comment by riseshia** [comment]
Hi, @wicky-info it seems your problem is solved, so let me close this issue. :)
