### ISSUE TITLE
Content of summernote not sent to controller

### ISSUE THREAD

**Issue by nhinze** [summernote/summernote-rails#58]
The content of summer note is not sent to the controller. As you can see in the log below, content => "" is empty. I have set my strong parameters:

`params.require(:info_page).permit(:organizer_id, :name, :content)`

Using:
- Rails 4.2.7.1
- Ruby 2.2.5
- Summernote 0.8.2

Code:

```
<%= bootstrap_form_for @info_page, layout: :horizontal, label_col: 'col-sm-2', control_col: 'col-sm-4' do |f| %>

    <%= f.alert_message "Please fix the errors below." %>

    <%= f.text_field :name, autofocus: true %>

    <%= f.text_field_without_bootstrap :content, :label => 'Page', 'data-provider' => 'summernote' %>

    <%= f.form_group do %>
        <% if controller.action_name == 'new' %>
            <%= f.submit 'Save',  data: { disable_with: 'Please wait...' } %>
        <% else %>
            <%= f.submit 'Update',  data: { disable_with: 'Please wait...' } %>
        <% end %>
    <% end %>

<% end %>
```

Resulting HTML Source:

```
<form role="form" class="form-horizontal" id="new_info_page" action="/info_pages" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="&#x2713;" /><input type="hidden" name="authenticity_token" value="rNe6182rbHF/4O8lyOwSEd7xnJ0oP6yD2Vj/cWsCHkyQjb/wvSTAC2vvxnu0q1AGH0264vNTOWNuIthoEpNYow==" />

<div class="form-group">
<label class="control-label col-sm-2 required" for="info_page_name">Name</label>
<div class="col-sm-4">
<input autofocus="autofocus" class="form-control" type="text" name="info_page[name]" id="info_page_name" />
</div>
</div>

<input label="Page" data-provider="summernote" type="text" name="info_page[content]" id="info_page_content" />

<div class="form-group">
<div class="col-sm-4 col-sm-offset-2">
<input type="submit" name="commit" value="Save" data-disable-with="Please wait..." class="btn btn-default" />
</div>
</div>

</form>
```

Resulting markup:

![summernote](https://cloud.githubusercontent.com/assets/1156143/21626232/f832d666-d1dd-11e6-88b8-5031286adf2e.jpg)

Log:

Started POST "/info_pages" for 127.0.0.1 at 2017-01-03 17:57:00 -0500
Processing by InfoPagesController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"rNe6182rbHF/4O8lyOwSEd7xnJ0oP6yD2Vj/cWsCHkyQjb/wvSTAC2vvxnu0q1AGH0264vNTOWNuIthoEpNYow==", "info_page"=>{"name"=>"Test", "content"=>""}, "files"=>"", "commit"=>"Save"}
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["id", 105]]
  Organizer Load (0.2ms)  SELECT  "organizers".* FROM "organizers" WHERE "organizers"."user_id" = $1 LIMIT 1  [["user_id", 105]]
   (0.1ms)  BEGIN
  SQL (0.2ms)  INSERT INTO "info_pages" ("name", "content", "organizer_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["name", "Test"], ["content", ""], ["organizer_id", 3], ["created_at", "2017-01-03 22:57:00.958472"], ["updated_at", "2017-01-03 22:57:00.958472"]]
   (0.2ms)  COMMIT
   (0.1ms)  BEGIN
   (0.1ms)  COMMIT
Redirected to http://0.0.0.0:5000/info_pages/2
Completed 302 Found in 10ms (ActiveRecord: 1.3ms)

**Comment by nhinze** [comment]
I figured out the problem. The ruby gem readme failed to mention that code is needed to update the input field:

```
$(document).on "page:change", ->
    $("#info_page_content").summernote
      callbacks: onChange: (contents, $editable) ->
        $("#info_page_content").val(contents)
        return
    code = $('#info_page_content').val()
    if code.length > 0
      $('#info_page_content').summernote 'code', code
      return
```

**Comment by SimonBo** [comment]
Had to the same hack in Rails 3.2, summernote-rails (0.8.3.0). But it works without the hack in rails 4.2 and  summernote-rails (0.6.6.0).
