### ISSUE TITLE
Pasting google sheets table doesn't persist the styling in IE 10/11

### ISSUE THREAD

**Issue by Reyko** [summernote/summernote-rails#60]
Tried pasting a table from google sheets and the editor removed the styling 

<img width="803" alt="screen shot 2017-01-31 at 14 37 27" src="https://cloud.githubusercontent.com/assets/350425/22469573/63489138-e7c4-11e6-836d-6a52abf6c6c0.png">

<img width="1219" alt="screen shot 2017-01-31 at 14 36 29" src="https://cloud.githubusercontent.com/assets/350425/22469572/6348171c-e7c4-11e6-9854-7a1a8830431f.png">

**Comment by riseshia** [comment]
I think it's summernote own problem. go [there](https://github.com/summernote/summernote/issues)
