### ISSUE TITLE
Does it only work with simple form?

### ISSUE THREAD

**Issue by jmurphy45** [summernote/summernote-rails#62]
There's no documentation on using form_for

**Comment by WaKeMaTTa** [comment]
You can use summernote with `form_for`:

```erb
<%# your view %>
<%= form_for :person do |f| %>
  <%= f.text_field :first_name, data: { provider: 'summernote' } %>
  <%= f.submit %>
<% end %>
```

**Comment by riseshia** [comment]
there is various way to do this unless there is no document about that.
the point is, you need some identifier to trigger summernote initialization.

and your comment is reasonable to agree. I will write some example for that If I have a time ;)
