### ISSUE TITLE
Empty toolbar buttons

### ISSUE THREAD

**Issue by coderdave** [summernote/summernote-rails#67]
I'm using rails 4.2.9 and I've upgraded summernote-rails to 0.8.2.0 but now the toolbar buttons are empty. I'm requiring summernote in application.js and importing it in the application.scss file. What am I missing?

![empty toolbar buttons](https://user-images.githubusercontent.com/964751/28268076-cd28db24-6aca-11e7-9512-eddb74396f54.png)

**Comment by sureseam** [comment]
You don't say what version you are upgrading from; which might help - some leaps are bigger than others.

You appear to be possibly missing a line or two in your **app/assets/stylesheets/application.scss**

On a Rails 4.2 project of mine the key parts look like this:
```
@import "bootstrap-sprockets";
@import "bootstrap";
@import "bootstrap/theme";
@import "font-awesome";
@import "summernote";
```

I think a proportion of the CSS comes via a gem called: 'font-awesome-rails'

Hope something there helps, if not further digging is plausible.
Regards A

**Comment by coderdave** [comment]
I'm upgrading from summernote version 0.6.6.0. I have all of those gems and imports in my scss file.

**Comment by coderdave** [comment]
I narrowed it down a bit further. When I upgrade to `0.7.1.0` it's fine. However, when I go to version `0.8.1.0 `, the buttons are blank.

**Comment by sureseam** [comment]
Two thoughts:
a)  If you operating in PRODUCTION mode then you might just need an asset precompile to be rerun. 
b) There is a 'conforg' project under my GitHub account where Summernote (8.1.1?) works fine; if that helps.

**Comment by coderdave** [comment]
I figured it out. I started to use the summernote library manually, by putting it under the vendor directory and lo and behold, I discovered an over THREE year old `summernote.css` file in there! Once I removed that, upgrading to the latest `0.8.1.0` worked! I'm surprised it was working at all with such an old file in there.
