### ISSUE TITLE
Update with the latest Summernote version

### ISSUE THREAD

**Issue by amrfaisal** [summernote/summernote-rails#71]
Do you plan to update the gem with the latest Summernote version `v0.8.8`?

**Comment by WaKeMaTTa** [comment]
They forgot to create a release. You can use master for now ;)

**Comment by amrfaisal** [comment]
@WaKeMaTTa What can we do to grab their attention to this?

**Comment by WaKeMaTTa** [comment]
cc/ @luciuschoi @hackerwins

**Comment by amrfaisal** [comment]
Any update on this?

**Comment by rorlab** [comment]
I'm sorry to be late.
I have just released v0.8.8.0 to Rubygems.org.
You can get the example project at [https://github.com/luciuschoi/summernote088](https://github.com/luciuschoi/summernote088)
And as soon as possbile, I'll update the example source of this repository with the above example project.

**Comment by rorlab** [comment]
Yep, I have just updated the example project of this repo.
Now, I'll update the README.md.

**Comment by rorlab** [comment]
Alright!

**Comment by luciuschoi** [comment]
Here you are.
Now `summernote-rails` gem has been just updated to v0.8.9.0 with summernote v0.8.9 and released to rubygems.org.

**Comment by amrfaisal** [comment]
Thanks a lot!!
