### ISSUE TITLE
Font Bold/Underline/Italic not working in V0.8.9.2

### ISSUE THREAD

**Issue by m-z-b** [summernote/summernote-rails#72]
To reproduce.

1. Clone current commit 51cd81d (Version 0.8.9.2)
2. Build the example project, and navigate to the home page in Firefox 58.0.1 or Edge 41.16299.15.0
3. Create a New Post, type some text, and attempt to Bold some of it.
4. Nothing happens, whether by using the keyboard accelerator CTRL-B or by clicking the button
5. Javascript console does not report any errors when using Firefox.

Other buttons not related to font bold/underline/italic/etc. seem to be working normally. 

Current version of summernote (as seen live at summernote.org) does not have this issue.

**Comment by luciuschoi** [comment]
OK. @hackerwin will fix this as soon as possible.

**Comment by jonalport** [comment]
Yep I am finding this too. The bold & italic buttons don't change the markup.

**Comment by Aflier** [comment]
OK. Did not see that bootstrap went to 4.0.0. I'll try updating them :)

**Comment by luciuschoi** [comment]
Yepp!
@hackerwins have finally fixed this bugs due to bootstrap version mismatch. He updated summernote-bs4.css with Bootstrap 4.0.0 from 4.0.0.beta.
Now, all buttons works well.

**Comment by saadtanvir1994** [comment]
Please add 
.note-editable b{font-weight:800;} 
to your summernote.css file.

**Comment by victorybiz** [comment]
This worked for me on bootstrap 4
`
/* Please add to your summernote.css / summernote-bs4.css file to fix bold. */
`
`
.note-editable b, .note-editable strong { font-weight: bold; }
`

To fix bold, undeline, etc, use the uncompressed javascript or re-minify the javascript because there seems to be an issue in the minified version of `v0.8.9`

**Comment by regololab** [comment]
I have this problem. The bold key is always active but does not work.
I use bootstrap 4.3.1.

**Comment by AlexanderBV** [comment]
@regololab  I have the same problem, I am using Bootstrap v4.3.1 
![image](https://user-images.githubusercontent.com/20906718/69484771-498faf00-0e05-11ea-9539-1109a984824c.png)
