### ISSUE TITLE
Release v0.8.12.0

### ISSUE THREAD

**Issue by SebouChu** [summernote/summernote-rails#84]
Pull request merged, a simple `rake release` should do the trick 🎉

Thank you! @hackerwins @luciuschoi

**Comment by SebouChu** [comment]
Hey @luciuschoi ! Do you happen to have release permission on this gem? 😊

**Comment by luciuschoi** [comment]
I'm so sorry to be late.
I've just released to rubygems.org with version 0.8.12
Now, you can just added summernote-rails gem without :github option.
